const RESERVED_USERNAMES = new Set([
  // Brand & product names
  "inai",
  "inailk",
  "inai_lk",
  "inai-lk",
  "ahkennexus",
  "ahken",
  "ahkenlab",
  "ahken-lab",
  "ahken_lab",

  // Generic platform words
  "admin",
  "administrator",
  "support",
  "help",
  "contact",
  "team",
  "staff",
  "official",
  "mod",
  "moderator",
  "system",
  "root",
  "superuser",
  "api",
  "dev",
  "developer",
  "test",
  "demo",
  "staging",
  "beta",

  // App route segments — would conflict with real pages
  "dashboard",
  "login",
  "logout",
  "register",
  "signup",
  "profile",
  "settings",
  "account",
  "business",
  "businesses",
  "public",
  "search",
  "explore",
  "home",
  "about",
  "terms",
  "privacy",
  "blog",
  "news",
  "press",
  "jobs",
  "careers",
  "partners",
  "advertise",
  "null",
  "undefined",
]);

export function isReservedUsername(username: string): boolean {
  return RESERVED_USERNAMES.has(username.toLowerCase());
}
